-- BOBU Genesis Portal v1.5
-- Run in Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.genesis_members (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  bobonaut_name text not null check (char_length(bobonaut_name) between 2 and 24),
  wallet_address text not null unique check (char_length(wallet_address) between 32 and 44),
  x_username text not null unique,
  telegram_username text not null unique,
  instagram_username text not null unique,
  bobu_points integer not null default 0 check (bobu_points >= 0),
  status text not null default 'genesis_member' check (status in ('genesis_member','waitlist','disqualified')),
  terms_version text not null default '1.0',
  created_at timestamptz not null default now()
);

create index if not exists genesis_members_created_at_idx on public.genesis_members(created_at);
create index if not exists genesis_members_points_idx on public.genesis_members(bobu_points desc);

alter table public.genesis_members enable row level security;

-- Public visitors may register. Unique constraints prevent repeated wallet/social entries.
drop policy if exists "public can register genesis member" on public.genesis_members;
create policy "public can register genesis member"
on public.genesis_members for insert
to anon, authenticated
with check (
  status in ('genesis_member','waitlist')
  and bobu_points = 0
);

-- Public visitors may only read the fields needed for the counter.
-- The frontend uses an exact count and does not download member rows.
drop policy if exists "public can count genesis members" on public.genesis_members;
create policy "public can count genesis members"
on public.genesis_members for select
to anon, authenticated
using (status = 'genesis_member');

-- Prevent clients from editing or deleting rows. Admin work should use Supabase dashboard
-- or a protected server/Edge Function. Never expose the service_role key in GitHub Pages.

create or replace function public.enforce_genesis_capacity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  approved_count bigint;
begin
  select count(*) into approved_count
  from public.genesis_members
  where status = 'genesis_member';

  if approved_count >= 1000 then
    new.status := 'waitlist';
  end if;
  return new;
end;
$$;

drop trigger if exists set_genesis_capacity on public.genesis_members;
create trigger set_genesis_capacity
before insert on public.genesis_members
for each row execute function public.enforce_genesis_capacity();
